spring:
  datasource:
      url: jdbc:mysql://192.168.7.25:3306/ck_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        initial-size: 2
        min-idle: 2
        max-active: 20
        max-wait: 30000
        query-timeout: 10
        test-on-borrow: true
        stat-view-servlet:
          loginUsername: admin
          loginPassword: admin
          allow: 127.0.0.1
          reset-enable: false
  rabbitmq:
      host: ${RABBIT_MQ_HOST:192.168.0.117}
      port:  ${RABBIT_MQ_PORT:5672}
      username: admin
      password: admin
  redis:
      database: 1
      host: ${REDIS_HOST:192.168.0.117}
      port: ${REDIS_PORT:6379}
      password:
      pool:
          max-active: 20

cron:
  user: 0 0/5 * * * *